@startuml Diagramme Packages
together {
package "business_object" {
    class Manga
    class Avis
    class Utilisateur
    class Collection_physique
    class CollectionCoherente
    class MangaPossede
}

package "dao" {
    class MangaDAO
    class AvisDAO
    class CollectionCoherenteDAO
    class CollectionPhysiqueDAO
    class DBConnection(metaclass=Singleton)
    class MangaPossedeDao
    class UtilisateurDao(metaclass=Singleton)
}

package "service" {
    class MangaService
    class AvisService
    class CollectionCoherenteService
    class Collection_physique_service
    class RechercheService
    class UtilisateurService
}

package "vue" {
    abstract class VueAbstraite
    class AccueilVue
    class InscriptionVue
    class AjouterAvisVuerecherche
    class AjouterMangaCollecVuerecherche
    class AjouterMangaPossCollPhys
    class MenuAvis
}

package "utils" {
    class LogIndetation
    class ResetDatabase(metaclass=Singleton)
    class Singleton(type)
    }
}

"vue" --> "service" : Utilise
"service" --> "dao" : Utilise
"service" --> "business_object" : Manipule
"dao" --> "business_object" : Manipule
"utils" --> "dao" : Fournit outils
"utils" --> "service" : Fournit outils
@enduml
